"""Check firmware GPIO assignments against the exported KiCad IC pin audit.

The audit is regenerated by BalancerREF/scripts/verify_netlist.py, so this test
is only as current as the last run of that. Every signal firmware names must
appear here - a pin added to board.hpp but not to `expected` passes silently.
"""
from pathlib import Path
import csv
import re

root = Path(__file__).resolve().parents[2]
header = (root/'firmware/src/board.hpp').read_text()
# Scan ONLY the constexpr declarations, not the whole file. Reading every `name=123`
# in the text meant a comment could invent a pin: the BQ24075 EN1/EN2 truth table is
# written out as `EN2=1 EN1=0`, and that was picked up as two GPIO assignments.
decls = ';'.join(re.findall(r'^\s*constexpr\s+int\s+([^;]*);', header, re.M))
pins = {k:int(v) for k,v in re.findall(r'\b(\w+)=(\d+)', decls)}
expected = {
    'accelSck':'ACCEL_SCK', 'accelMosi':'ACCEL_MOSI', 'accelMiso':'ACCEL_MISO', 'accelCs':'ACCEL_CS', 'drdy':'ACCEL_DRDY',
    'mag':'MAG_TACH', 'opt':'OPT_TACH', 'emitter':'OPT_LED_EN',
    'acquire':'ACQUIRE_BUTTON', 'led':'STATUS_LED', 'supplyAdc':'SUPPLY_SENSE',
    'usbDm':'USB_D-_MCU', 'usbDp':'USB_D+_MCU',
    # BQ24075 charger control and status
    'chgEn1':'CHG_EN1', 'chgEn2':'CHG_EN2', 'pgood':'PGOOD_N', 'chgStat':'CHG_STAT',
    'gpsTx':'GPS_UART_TX', 'gpsRx':'GPS_UART_RX', 'gpsPps':'GPS_PPS',
}
rows = list(csv.reader((root/'review/IC-pin-audit.csv').open()))
gpio_nets = {}
for row in rows[1:]:
    ref,pad,function,net,*rest = row
    if ref=='U1' and (match:=re.match(r'GPIO(\d+)', function)):
        gpio_nets[int(match[1])] = (pad,net)
for name,signal in expected.items():
    pad,net = gpio_nets[pins[name]]
    if name.startswith('usb'):
        # Series resistors create unnamed MCU-side nets using the module USB pin name.
        assert ('USB_D-' if name=='usbDm' else 'USB_D+') in net, (name,pad,net)
    else:
        assert net.lstrip('/')==signal, (name,pad,net)
# Catch the silent-gap case: every numeric pin in board.hpp must be covered here.
unchecked = sorted(set(pins) - set(expected))
assert not unchecked, f'board.hpp pins not covered by this test: {unchecked}'
print(f'PASS: {len(expected)} GPIO assignments match the KiCad physical-pad audit; '
      f'all {len(pins)} board.hpp pins covered.')
